tio/blog/urls.py
# blog/urls.py

from django.urls import path
from .views import (PostListView, PostDetailView, CategoryPostListView, AboutView, ContactView, PostSearchView, TaggedPostListView)
from django.contrib.sitemaps.views import sitemap
from .sitemap import PostSitemap
from .views import NewsletterSubscribeView

sitemaps = {'posts': PostSitemap}


urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('category/<int:category_id>/', CategoryPostListView.as_view(), name='category_posts'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('search/', PostSearchView.as_view(), name='post_search'),
    path('tag/<slug:slug>', TaggedPostListView.as_view(), name='tagged_posts'),
    path('subscribe/', NewsletterSubscribeView.as_view(), name='newsletter_subscribe'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

tio/tio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

# Add this at the end to serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tio/blog/models.py
# blog/models.py
import uuid
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


# class CustomUser(AbstractUser):
#     pass


class Post(models.Model):
    # uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    # slug = models.SlugField(max_length=200, unique=True, editable=False)
    title = models.CharField(max_length=200)
    scripture = RichTextField()  # Daily scripture
    exegesis = RichTextField() # Metaphysical exegesis
    application = RichTextField()  # Daily application of the scripture
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    tags = TaggableManager()
    is_featured = models.BooleanField(default=False)
    views = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.uuid})

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         if self.title:
    #             self.slug = slugify(self.title)
    #         else:
    #             self.slug = slugify(str(self.uuid))
    #     super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class PostView(models.Model):
    post = models.ForeignKey(Post, related_name='post_views', on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField()
    viewed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.ip_address} viewed {self.post.title}'


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Comment by {self.author}'

tio/blog/forms.py
# blog/forms.py

from django import forms
from .models import Comment
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'body']


class NewsletterForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={
        'placeholder': 'Enter your email', 'class': 'form-control'
    }))


# class CustomUserCreationForm(UserCreationForm):
#     model = get_user_model()
#     fields = {
#         'email',
#         'username',
#     }
#
#
# class CustomUserChangeForm(UserChangeForm):
#     class Meta:
#         model = get_user_model()
#         fields = {
#             'email',
#             'username',
#         }

tio/blog/views.py
# blog/views.py

from django.views.generic import ListView, DetailView, FormView, TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q
from .models import Post, Category, PostView
from .forms import CommentForm
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Count
from .forms import NewsletterForm
from .newsletter_util import subscribe_email_to_mailchimp


# from ratelimit.decorators import ratelimit


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 3

    # post_numbs = Post.objects.all().aggregate(post_numbs=Count('id'))

    def get_context_data(self, **kwargs):
        # Add categories to the context for filtering
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['post_numbs'] = Post.objects.all().aggregate(post_numbs=Count('id'))
        return context

    def get_queryset(self):
        """Override this method to customize the query."""
        return Post.objects.all().order_by('-created_at')  # Show most recent posts first

    def get(self, request, *args, **kwargs):
        # If this is an AJAX request, handle pagination dynamically
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            page = request.GET.get('page')
            posts = self.get_queryset()
            paginator = Paginator(posts, self.paginate_by)
            try:
                posts = paginator.page(page)
            except Exception as e:
                return JsonResponse({'error': str(e)}, status=400)

            # Return only the rendered posts HTML
            posts_html = self.render_to_string('blog/post_partial_list.html', {'posts': posts})
            return JsonResponse({'posts_html': posts_html})

        return super().get(request, *args, **kwargs)

    def render_to_string(self, template_name, context):
        """Helper function to render template as a string for AJAX requests."""
        from django.template.loader import render_to_string
        return render_to_string(template_name, context)


# 2. DetailView for viewing individual posts and comments
class PostDetailView(DetailView, FormView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        # Add comments and form to the context
        context = super().get_context_data(**kwargs)
        context['comments'] = self.get_object().comments.all()
        context['comment_form'] = self.get_form()
        context['related_posts'] = Post.objects.filter(category=self.object.category).exclude(id=self.object.id)[:3]
        return context

    # def get_object(self, queryset=None):
    #     return get_object_or_404(Post, slug=self.kwargs['slug'])

    def get_client_ip(self, request):
        # Helper method to get the client's IP address
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def get(self, request, *args, **kwargs):
        post = self.get_object()

        # Get the user's IP address
        ip_address = self.get_client_ip(request)

        # Check if this IP has viewed the post before
        if not PostView.objects.filter(post=post, ip_address=ip_address).exists():
            # If not, increment the view count and log the IP
            post.views += 1
            post.save(update_fields=['views'])
            # Save the view record
            PostView.objects.create(post=post, ip_address=ip_address)

        # Proceed with the usual `get` behavior
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Handle comment form submission
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.object
            comment.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.form_invalid(form)


# class PostDetailByUUIDView(DetailView, FormView):
#     model = Post
#     template_name = 'blog/post_detail.html'
#     context_object_name = 'post'
#     form_class = CommentForm
#
#     def get_context_data(self, **kwargs):
#         # Add comments and form to the context
#         context = super().get_context_data(**kwargs)
#         context['comments'] = self.get_object().comments.all()
#         context['comment_form'] = self.get_form()
#         context['related_posts'] = Post.objects.filter(category=self.object.category).exclude(id=self.object.id)[:3]
#         return context
#
#     def get_object(self, queryset=None):
#         return get_object_or_404(Post, uuid=self.kwargs['uuid'])
#
#     def get_client_ip(self, request):
#         # Helper method to get the client's IP address
#         x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
#         if x_forwarded_for:
#             ip = x_forwarded_for.split(',')[0]
#         else:
#             ip = request.META.get('REMOTE_ADDR')
#         return ip
#
#     def get(self, request, *args, **kwargs):
#         post = self.get_object()
#
#         # Get the user's IP address
#         ip_address = self.get_client_ip(request)
#
#         # Check if this IP has viewed the post before
#         if not PostView.objects.filter(post=post, ip_address=ip_address).exists():
#             # If not, increment the view count and log the IP
#             post.views += 1
#             post.save(update_fields=['views'])
#             # Save the view record
#             PostView.objects.create(post=post, ip_address=ip_address)
#
#         # Proceed with the usual `get` behavior
#         return super().get(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         # Handle comment form submission
#         self.object = self.get_object()
#         form = self.get_form()
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = self.object
#             comment.save()
#             return redirect(self.object.get_absolute_url())
#         else:
#             return self.form_invalid(form)
#

# 3. ListView for listing posts filtered by category
class CategoryPostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = ['-created_at']

    def get_queryset(self):
        # Get posts only within the selected category
        category = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return Post.objects.filter(category=category).order_by('-created_at')

    def get_context_data(self, **kwargs):
        # Add categories and selected category to the context
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['selected_category'] = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return context


class TaggedPostListView(ListView):
    model = Post
    template_name = 'blog/tagged_post.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs.get('slug')
        return context


# 4. TemplateView for the About page
class AboutView(TemplateView):
    template_name = 'blog/about.html'


# 5. TemplateView for the Contact page
class ContactView(TemplateView):
    template_name = 'blog/contact.html'


class PostSearchView(ListView):
    model = Post
    template_name = 'blog/post_search.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Post.objects.filter(Q(title__icontains=query) | Q(exegesis__icontains=query))
        return Post.objects.none()


# @ratelimit(key='ip', rate='5/m', method='GET', block=True)
# def my_view(request):
#     return HttpResponse("This view is rate limited to 5 requests per minute.")


class NewsletterSubscribeView(FormView):
    template_name = 'blog/newsletter_subscribe.html'
    form_class = NewsletterForm
    success_url = reverse_lazy('newsletter_subscribe')

    def form_valid(self, form):
        email = form.cleaned_data['email']

        # Subscribe email to Mailchimp
        status_code, response_json = subscribe_email_to_mailchimp(email)

        if status_code == 200:
            # Send confirmation email
            send_mail(
                'Thank you for subscribing!',
                'You have successfully subscribed to our newsletter.',
                'your_email@example.com',
                [email],
                fail_silently=False,
            )

            # Show success message on the website
            messages.success(self.request, 'You have successfully subscribed to our newsletter!')
        else:
            # If Mailchimp subscription fails
            messages.error(self.request, 'There was an issue subscribing. Please try again.')

        # Redirect to success URL
        return super().form_valid(form)

    def form_invalid(self, form):
        # Show error message if the form is invalid
        messages.error(self.request, 'Invalid email. Please try again.')
        return super().form_invalid(form)

tio/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}About Us - The Incurable Optimist{% endblock %}

{% block content %}
    <div class="comment">
            <h1>About Me</h1>
            <p>
                Welcome to The Incurable Optimist Blog! This blog is dedicated to sharing daily scriptures with metaphysical exegesis and practical applications to life.
            </p>
            <p>
                I am passionate about spiritual growth and helping others find deeper meaning in their lives, hence I have given myself to spiritual studies.
            </p>
            <p>
                My mission is to inspire and guide spiritual growth seekers and metaphysical enthusiasts by providing daily reflections that promote positivity, healing, and effective living.
            </p>
    </div>
{% endblock %}

tio/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}The Incurable Optimist | Daily Scriptures for Spiritual Growth{% endblock %}</title>

    <!-- Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&family=Lato:wght@400;700&family=Lora:wght@400;700&family=Merriweather:wght@400;700&family=Open+Sans:wght@400;700&family=Playfair+Display:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'image/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'image/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'image/favicon_io/site.webmanifest' %}">

    <!-- Alpine.js for interactivity -->
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body class="bg-gray-100 text-gray-900">

    <!-- Navigation Bar -->
<header class="bg-indigo-700 text-white">
    <div class="container mx-auto p-6 flex flex-col md:flex-row justify-between items-center">
        <div class="text-center md:text-left">
            <h1 class="text-4xl font-bold">The Incurable Optimist</h1>
            <p class="mt-2">Daily Scriptures with Metaphysical Exegesis and Life Applications</p>
        </div>
<!--        <nav class="mt-4 md:mt-0">-->
        <nav class="flex items-center justify-between p-4 text-white">

            <!-- Hamburger icon for mobile -->
            <button class="navbar-toggle block lg:hidden text-3xl focus:outline-none" id="navbar-toggle">
                &#9776; <!-- Hamburger icon -->
            </button>

            <ul class="nav-links hidden lg:flex space-x-4" id="nav-link">
                <li><a href="{% url 'post_list' %}" class="hover:text-white">TIO</a></li>
                <li><a href="{% url 'about' %}" class="hover:text-white">About</a></li>
                <li><a href="{% url 'contact' %}" class="hover:text-white">Contact</a></li>
                <li><a href="#" id="newsletter-link" class="cursor-not-allowed hover:text-white">Newsletter</a></li>
<!--                <li><a href="{% url 'newsletter_subscribe' %}" class="hover:text-white" target="_self" id="newsletter-link">Newsletter</a></li>-->
            </ul>
        </nav>
    </div>

    <form class="search-form" action="{% url 'post_search' %}" method="GET">
        <input class="search-input" type="text" name="q" placeholder="Search posts..." required>
        <button class="search-button" type="submit">Search</button>
    </form>
</header>


    <!-- Content -->
    <main class="container mx-auto py-10">
        {% block content %}{% endblock %}
    </main>

    <!-- Footer -->
    <footer class="bg-indigo-700 text-white mt-10">
        <div class="container mx-auto p-6 flex justify-between items-center">
            <p>&copy; 2024 The Incurable Optimist. All rights reserved.</p>
            <a href="#" id="newsletter-link" class="cursor-not-allowed hover:text-white">Newsletter</a>
<!--            <a href="{% url 'newsletter_subscribe' %}" target="_self"><b>Subscribe to Newsletter</b></a>-->
            <div>
                <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                <a href="https://linkedin.com" target="_blank"><i class="fab fa-linkedin-in"></i></a>
            </div>
        </div>
    </footer>

    <script src="{% static 'blog/navbar.js' %}">{% block extra_scripts %}{% endblock %}</script>
    <script src="{% static 'blog/navbar.js' %}"></script>
</body>
</html>

tio/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}Contact Me - The Incurable Optimist{% endblock %}

{% block content %}
    <div class="comment">
        <h1>Contact Me</h1>
        <p>If you have any questions or would like to get in touch, feel free to contact me at:</p>
        <p><strong>Email:</strong> contact@theincurableoptimist.com</p>
        <p><strong>Phone:</strong> +233 548 847490</p>
    </div>
{% endblock %}

tio/blog/templates/blog/newsletter_subscribe.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<section class="newsletter bg-indigo-700 text-white rounded-lg">
    <h2 class="text-3xl font-bold text-center">Subscribe to my Newsletter</h2>
    <h5 class="text-2xl mt-4 text-center">Embrace Metaphysical Optimism</h5>
    <p class="text-center text-lg mt-4">through weekly metaphysical insights </p>
    <p class="text-center text-lg mt-4">for excellent and abundant living</p>
    <p class="text-center text-lg mt-4">delivered directly to your inbox.</p>

    <form id="newsletter-form" class="flex justify-center mt-6" method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="news bg-white text-indigo-700 rounded-r font-bold" aria-label="Subscribe to The Incurable Optimist Blog">Subscribe</button>
  </form>
</section>


  {% if messages %}
      <ul class="messages">
          {% for message in messages %}
              <li> {% if message.tags %} class="{{ message.tags }}"{% endif %}{{ message }}</li>
          {% endfor %}
      </ul>
  {% endif %}
<script src="{% static 'blog/newsletter_alert.js' %}"></script>

{% endblock %}

tio/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}

    <!-- Dynamic Title: Use the Post Title -->
    <title>{{ post.title }} | The Incurable Optimist</title>

    <!-- Meta Description: Provide a summary of the post -->
    <meta name="description" content="{{ post.exegesis|truncatewords:25 }}">

    <!-- Keywords: Optional, but could include the post's category and important terms -->
    <meta name="keywords" content="spiritual growth, metaphysical exegesis, {{ post.category.name }}, daily scripture, {{ post.title }}">

    <!-- Open Graph Meta Tags for Social Sharing -->
    <meta property="og:title" content="{{ post.title }} | The Incurable Optimist">
    <meta property="og:description" content="{{ post.exegesis|truncatewords:25 }}">
    <meta property="og:image" content="{% if post.image %}{{ post.image.url }}{% else %}{% static 'blog/logo.png' %}{% endif %}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{{ post.title }} | The Incurable Optimist">
    <meta name="twitter:description" content="{{ post.exegesis|truncatewords:25 }}">
    <meta name="twitter:image" content="{% if post.image %}{{ post.image.url }}{% else %}{% static 'blog/logo.png' %}{% endif %}">

    <!-- Canonical URL -->
    <link rel="canonical" href="{{ request.build_absolute_uri }}">

{% block title %}{{ post.title }} | The Incurable Optimist{% endblock %}

{% block content %}
    <!-- Progress Bar Container -->
    <div class="progress-container">
        <div class="progress-bar" id="progressBar"></div>
    </div>

    <!-- Post Content -->
    <article class="bg-white shadow-lg rounded-lg p-8 mb-10">
        <h1 class="text-4xl font-bold mb-4">{{ post.title }}</h1>
        <p class="text-sm text-gray-500 mb-4">Posted on {{ post.created_at }} | Category: {{ post.category.name }} | Author: {{ post.author }}</p>
        <p class="text-sm text-gray-500 mb-4"></p>
        <!-- Post Image (Optional) -->
        {% if post.image %}
            <div class="my-4">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="w-full max-w-xl mx-auto rounded-lg shadow-md">
            </div>
        {% endif %}

        <section class="mb-8">
            <h2 class="text-2xl font-bold mb-2">Scripture</h2>
            <p class="text-gray-700">{{ post.scripture|safe }}</p>
        </section>

        <section class="mb-8">
            <h2 class="text-2xl font-bold mb-2">Metaphysical Exegesis</h2>
            <p class="text-gray-700">{{ post.exegesis|safe }}</p>
        </section>

        <section class="mb-8">
            <h2 class="text-2xl font-bold mb-2">Life Application</h2>
            <p class="text-gray-700">{{ post.application|safe }}</p>
        </section>

        <p class="post-views">
            <i class="fas fa-eye"></i>  <!-- Eye icon -->
            {{ post.views }} views
        </p>


                <!-- Social Media Sharing Section -->
        <div class="social-sharing">
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="btn-facebook" aria-label="Share on Facebook"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ post.title }}" target="_blank" class="btn-twitter" aria-label="Share on Twitter"><i class="fab fa-twitter"></i></a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ post.title }}" target="_blank" class="btn-linkedin" aria-label="Share on LinkedIn"><i class="fab fa-linkedin-in"></i></a>
            <p> ← Share </p>
        </div>

        <div class="tags mt-4">
            <h6 class="text-xl font-bold">Tags:</h6>
            <ul class="flex space-x-2">
                {% for tag in post.tags.all %}
                    <li><a href="{% url 'tagged_posts' tag.slug %}" class="bg-gray-200 text-gray-700 px-2 py-1 rounded-lg">{{ tag.name }}</a></li>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </ul>
        </div>

    </article>

<!-- Comments Section -->
    <section class="mb-10">
        <h2 class="comment text-3xl font-bold mb-6">Comments</h2>

        <ul class="space-y-4 comment">
            {% for comment in comments %}
                <li class="bg-white shadow-lg rounded-lg p-4">
                    <p class="text-gray-600"><strong>{{ comment.author }}</strong> said:</p>
                    <p class="mt-2">{{ comment.body }}</p>
                    <p class="text-sm text-gray-400 mt-2">{{ comment.created_at }}</p>
                </li>
            {% empty %}
                <li class="comment">No comments yet. Be the first to comment!</li>
            {% endfor %}
        </ul>
    </section>

<!-- Toggle Comment Form Visibility -->
    <section class="comment" x-data="{ showForm: false }">
    <button @click="showForm = !showForm" class="bg-indigo-700 text-white px-6 py-3 rounded-lg font-bold">Leave a Comment</button>

    <!-- Comment Form (Toggled Visibility) -->
        <div x-show="showForm" class="mt-6">
            <form method="POST" class="bg-white shadow-lg rounded-lg p-6">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="id_author" class="block text-gray-700 font-bold mb-2">Name:</label>
                    <input type="text" name="author" id="id_author" class="w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Your name">
                </div>

                <div class="mb-4">
                    <label for="id_body" class="block text-gray-700 font-bold mb-2">Comment:</label>
                    <textarea name="body" id="id_body" class="w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Your comment"></textarea>
                </div>
                <button type="submit" class="bg-indigo-700 text-white px-6 py-3 rounded-lg font-bold">Submit</button>
            </form>
        </div>
    </section>


    <h3 class="related">Related Posts</h3>
    <ol class="related" type="1">
        {% for related_post in related_posts %}
            <li><a href="{% url 'post_detail' related_post.pk %}">{{ related_post.title }}</a></li>
        {% endfor %}
    </ol>

    <!-- Link to the JavaScript file -->
    <script src="{% static 'blog/navbar.js' %}"></script>
    <script src="{% static 'blog/load_more.js' %}"></script>
    <script src="{% static 'blog/progress.js' %}"></script>

{% endblock %}

tio/blog/templates/blog/post_partial_list.html
{% for post in posts %}
    <div class="post-card bg-white shadow-lg rounded-lg p-6">
        <h3 class="text-2xl font-semibold mb-2"><a href="{% url 'post_detail' post.pk %}" class="text-indigo-700 hover:underline">{{ post.title }}</a></h3>
        <p class="text-gray-600">{{ post.scripture|striptags|truncatewords:20|safe }}</p>
        <p class="text-sm text-gray-400 mt-4">Posted on {{ post.created_at }} | Category: {{ post.category.name }}</p>
        <a href="{% url 'post_detail' post.pk %}" class="text-indigo-700 font-bold mt-2 inline-block">Read More &rarr;</a>
    </div>
{% endfor %}

tio/blog/templates/blog/search_result.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Search Results for "{{ request.GET.q }}"</h2>
    {% if posts %}
        {% for post in posts %}
            <div>
                <h3><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h3>
                <p>{{ post.exegesis|truncatewords:30 }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}